title: Arawn Davies Portal
author: 
    name: Arawn Davies
    email: arawn@arawn-davies.co.uk
description:  
    The melting pot of software, hardware and experience


base_url: /
repository: Arawn-Davies/arawn-davies.github.io


rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: squidwhere
    github:  arawn-davies
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: arawn-davies
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote-theme: minima

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag


# Minima: custom header links
header_pages:
  - index.md
  - _pages/about.md
  - _pages/hiring.md
  - _pages/blog.md
  - projects/projects.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - _upstr

future: true
